# @name getToken
POST https://login.microsoftonline.com/{{tenantId}}/oauth2/v2.0/token HTTP/1.1
Content-Type: application/x-www-form-urlencoded

client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=client_credentials&scope={{clientScope}}


###


# Call GET on Protected API
GET https://{{apimHostname}}/protected HTTP/1.1
Authorization: Bearer {{getToken.response.body.access_token}}
