#=============================================================================
# Test requests for the Unprotected API
#=============================================================================

# Call GET on Unprotected API
GET https://{{apimHostname}}/unprotected HTTP/1.1

###

# Call POST on Unprotected API
POST https://{{apimHostname}}/unprotected HTTP/1.1

###

# Call DELETE on Unprotected API
DELETE https://{{apimHostname}}/unprotected HTTP/1.1
